CREATE OR REPLACE VIEW OPS.PLATFORM_HEALTH_DASHBOARD AS
SELECT
    CURRENT_TIMESTAMP AS snapshot_time,
    COUNT(*) AS total_tables,
    COUNT(DISTINCT data_owner) AS total_data_owners
FROM META.DATA_DICTIONARY;