USE WAREHOUSE EDP_WH;
USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.META;

INSERT INTO LINEAGE_MAP (
  TARGET_DATABASE, TARGET_SCHEMA, TARGET_TABLE, TARGET_COLUMN,
  SOURCE_DATABASE, SOURCE_SCHEMA, SOURCE_TABLE, SOURCE_COLUMN,
  TRANSFORMATION_RULE, TRANSFORMATION_TYPE, OWNER, CREATED_AT
)
VALUES
-- customer_id
('ENTERPRISE_DATA_PLATFORM_DB','STAGING','STG_CUSTOMERS','CUSTOMER_ID',
 'ENTERPRISE_DATA_PLATFORM_DB','RAW','OLIST_CUSTOMERS_RAW','CUSTOMER_ID',
 'TRIM(customer_id)', 'CLEANSE', 'Data Steward - Customer Domain', CURRENT_TIMESTAMP()),

-- customer_unique_id
('ENTERPRISE_DATA_PLATFORM_DB','STAGING','STG_CUSTOMERS','CUSTOMER_UNIQUE_ID',
 'ENTERPRISE_DATA_PLATFORM_DB','RAW','OLIST_CUSTOMERS_RAW','CUSTOMER_UNIQUE_ID',
 'DIRECT MAP', 'DIRECT', 'Data Steward - Customer Domain', CURRENT_TIMESTAMP()),

-- zip prefix
('ENTERPRISE_DATA_PLATFORM_DB','STAGING','STG_CUSTOMERS','CUSTOMER_ZIP_CODE_PREFIX',
 'ENTERPRISE_DATA_PLATFORM_DB','RAW','OLIST_CUSTOMERS_RAW','CUSTOMER_ZIP_CODE_PREFIX',
 'DIRECT MAP', 'DIRECT', 'Data Steward - Customer Domain', CURRENT_TIMESTAMP()),

-- city
('ENTERPRISE_DATA_PLATFORM_DB','STAGING','STG_CUSTOMERS','CUSTOMER_CITY',
 'ENTERPRISE_DATA_PLATFORM_DB','RAW','OLIST_CUSTOMERS_RAW','CUSTOMER_CITY',
 'DIRECT MAP (optionally TRIM later)', 'DIRECT', 'Data Steward - Customer Domain', CURRENT_TIMESTAMP()),

-- state
('ENTERPRISE_DATA_PLATFORM_DB','STAGING','STG_CUSTOMERS','CUSTOMER_STATE',
 'ENTERPRISE_DATA_PLATFORM_DB','RAW','OLIST_CUSTOMERS_RAW','CUSTOMER_STATE',
 'DIRECT MAP; validated by dbt tests (length=2, not null)', 'DIRECT', 'Data Steward - Customer Domain', CURRENT_TIMESTAMP());


 SELECT TARGET_TABLE, COUNT(*) AS lineage_rows
FROM ENTERPRISE_DATA_PLATFORM_DB.META.LINEAGE_MAP
GROUP BY TARGET_TABLE;

SELECT *
FROM ENTERPRISE_DATA_PLATFORM_DB.META.LINEAGE_MAP
WHERE TARGET_TABLE = 'STG_CUSTOMERS'
ORDER BY CREATED_AT DESC;