USE WAREHOUSE EDP_WH;
USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.META;

INSERT INTO LINEAGE_MAP (
  TARGET_DATABASE, TARGET_SCHEMA, TARGET_TABLE, TARGET_COLUMN,
  SOURCE_DATABASE, SOURCE_SCHEMA, SOURCE_TABLE, SOURCE_COLUMN,
  TRANSFORMATION_RULE, TRANSFORMATION_TYPE, OWNER, CREATED_AT
)
VALUES
-- order_id
('ENTERPRISE_DATA_PLATFORM_DB','STAGING','STG_ORDERS','ORDER_ID',
 'ENTERPRISE_DATA_PLATFORM_DB','RAW','OLIST_ORDERS_RAW','ORDER_ID',
 'TRIM(order_id)', 'CLEANSE', 'Data Steward - Order Domain', CURRENT_TIMESTAMP()),

-- customer_id
('ENTERPRISE_DATA_PLATFORM_DB','STAGING','STG_ORDERS','CUSTOMER_ID',
 'ENTERPRISE_DATA_PLATFORM_DB','RAW','OLIST_ORDERS_RAW','CUSTOMER_ID',
 'TRIM(customer_id)', 'CLEANSE', 'Data Steward - Order Domain', CURRENT_TIMESTAMP()),

-- order_status
('ENTERPRISE_DATA_PLATFORM_DB','STAGING','STG_ORDERS','ORDER_STATUS',
 'ENTERPRISE_DATA_PLATFORM_DB','RAW','OLIST_ORDERS_RAW','ORDER_STATUS',
 'DIRECT MAP', 'DIRECT', 'Data Steward - Order Domain', CURRENT_TIMESTAMP()),

-- purchase timestamp
('ENTERPRISE_DATA_PLATFORM_DB','STAGING','STG_ORDERS','ORDER_PURCHASE_TIMESTAMP',
 'ENTERPRISE_DATA_PLATFORM_DB','RAW','OLIST_ORDERS_RAW','ORDER_PURCHASE_TIMESTAMP',
 'DIRECT MAP; cast to timestamp if needed', 'DIRECT', 'Data Steward - Order Domain', CURRENT_TIMESTAMP()),

-- estimated delivery date
('ENTERPRISE_DATA_PLATFORM_DB','STAGING','STG_ORDERS','ORDER_ESTIMATED_DELIVERY_DATE',
 'ENTERPRISE_DATA_PLATFORM_DB','RAW','OLIST_ORDERS_RAW','ORDER_ESTIMATED_DELIVERY_DATE',
 'DIRECT MAP; cast to date if needed', 'DIRECT', 'Data Steward - Order Domain', CURRENT_TIMESTAMP());

 SELECT TARGET_TABLE, COUNT(*) AS lineage_rows
FROM ENTERPRISE_DATA_PLATFORM_DB.META.LINEAGE_MAP
GROUP BY TARGET_TABLE
ORDER BY TARGET_TABLE;