CREATE OR REPLACE VIEW OPS.DATA_VOLUME_MONITOR AS

SELECT
table_schema,
table_name,
row_count,
created

FROM ENTERPRISE_DATA_PLATFORM_DB.INFORMATION_SCHEMA.TABLES
WHERE table_schema IN ('RAW','STAGING','MART');