USE ROLE ACCOUNTADMIN;
USE WAREHOUSE EDP_WH;
USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA DQ;

CREATE OR REPLACE TABLE DQ_RUNS (
    RUN_ID       STRING,
    RUN_TS       TIMESTAMP_NTZ,
    TRIGGERED_BY  STRING,
    ENV          STRING,
    STATUS        STRING,
    NOTES         STRING
);

CREATE OR REPLACE TABLE DQ_TEST_RESULTS (
    RUN_ID    STRING,
    TEST_NAME      STRING,
    MODEL_NAME       STRING,
    SEVERITY         STRING, 
    STATUS             STRING,
    FAILURES         NUMBER,
    EXECUTED_AT        TIMESTAMP_NTZ,
    COMPILED_SQL         STRING  
);

SHOW TABLES IN SCHEMA ENTERPRISE_DATA_PLATFORM_DB.DQ;