USE WAREHOUSE EDP_WH;
USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.DQ;


SET RUN_ID = TO_VARCHAR(CURRENT_TIMESTAMP(),'YYYYMMDD_HH24MISS_FF3');

INSERT INTO DQ_RUNS ( RUN_ID, RUN_TS, TRIGGERED_BY, ENV, STATUS, NOTES)
SELECT 
    $RUN_ID, 
    CURRENT_TIMESTAMP(),
    CURRENT_USER(),
    'DEV',
    'STARTED',
    'Starting dbt test run';

   