USE WAREHOUSE EDP_WH;
USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA DQ;

UPDATE DQ_RUNS
SET STATUS = 'COMPLETED',
    NOTES = 'dbt test passed sucessfully'
WHERE RUN_ID = '20260225_204540_107';

SELECT RUN_ID, STATUS, RUN_TS
FROM DQ_RUNS
ORDER BY RUN_TS DESC;