USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA DQ;

UPDATE DQ_RUNS
SET STATUS = 'FAILED',
    NOTES = 'dbt test failed: accepted_values_stg_customers_customer_state__ZZ(27 failures)'
WHERE RUN_ID = '20260225_210235_867';

SELECT * FROM DQ_RUNS ORDER BY RUN_TS DESC LIMIT 3;
SELECT * FROM DQ_TEST_RESULTS ORDER BY EXECUTED_AT DESC LIMIT 5;

SELECT STATUS, COUNT(*) 
FROM DQ_RUNS
GROUP BY STATUS;