USE WAREHOUSE EDP_WH;
USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.DQ;

CREATE OR REPLACE TABLE DQ_EXCEPTIONS (
    RUN_ID        STRING,
    RULE_NAME     STRING, 
    MODEL_NAME    STRING, 
    PRIMARY_KEY   STRING,
    EXCEPTION_PAYLOAD   VARIANT,
    CREATED_AT     TIMESTAMP_NTZ
);

SHOW TABLES LIKE 'DQ_EXCEPTIONS' IN SCHEMA ENTERPRISE_DATA_PLATFORM_DB.DQ;