USE WAREHOUSE EDP_WH;
USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.DQ;


SET RUN_ID = TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MMSS_FF3');
SELECT $RUN_ID AS RUN_ID;

USE WAREHOUSE EDP_WH;
USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.DQ;

INSERT INTO DQ_RUNS(RUN_ID,RUN_TS, TRIGGERED_BY, ENV,STATUS,NOTES)
SELECT 
    $RUN_ID, 
    CURRENT_TIMESTAMP(),
    CURRENT_USER(),
    'DEV',
    'STARTED',
    'Logging exception samples for stg_customers rules';

INSERT INTO DQ_EXCEPTIONS (RUN_ID,RULE_NAME, MODEL_NAME, PRIMARY_KEY,EXCEPTION_PAYLOAD, CREATED_AT)

SELECT 
    $RUN_ID, 
    'STATE_CODE_LENGTH_2',
    'stg_customers',
    customer_id,
    OBJECT_CONSTRUCT(
        'customer_id', customer_id,
        'customer_state', customer_state,
        'customer_city', customer_city,
        'zip_prefix', customer_zip_code_prefix
    ),
    CURRENT_TIMESTAMP()
FROM ENTERPRISE_DATA_PLATFORM_DB.STAGING.STG_CUSTOMERS
WHERE customer_state IS NULL
    OR LENGTH(TRIM(customer_state)) <> 2
LIMIT 50;


UPDATE DQ_RUNS
SET STATUS = 'COMPLETED',
    NOTES = 'Exception samples captured for stg_customers'
WHERE RUN_ID = $RUN_ID;

SELECT RULE_NAME, COUNT(*) AS exception_rows
FROM DQ_EXCEPTIONS
WHERE RUN_ID = $RUN_ID
GROUP BY RULE_NAME;

SELECT *
FROM DQ_EXCEPTIONS
WHERE RUN_ID = $RUN_ID
LIMIT 5;