USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA DQ;


CREATE OR REPLACE VIEW DQ_SCORECARD AS 
SELECT 
  r.RUN_ID,
  r.RUN_TS,
  r.STATUS,
  COUNT(t.TEST_NAME)           AS total_tests_logged,
  COALESCE(SUM(t.FAILURES),0)  AS total_failures,
  CASE
    WHEN COUNT(t.TEST_NAME) = 0 THEN 100
    ELSE ROUND(
            100 * (COUNT(t.TEST_NAME) - COUNT_IF(t.STATUS = 'FAIL'))
            / COUNT(t.TEST_NAME),2
    )
  END AS pass_percentage
FROM DQ_RUNS r
LEFT JOIN DQ_TEST_RESULTS t
    ON r.RUN_ID = t.RUN_ID
GROUP BY r.RUN_ID, r.RUN_TS, r.STATUS;
        


  SELECT *
FROM DQ_SCORECARD
ORDER BY RUN_TS DESC;