USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.DQ;

CREATE OR REPLACE VIEW DQ_LATEST_RUN AS
SELECT *
FROM DQ_SCORECARD_V2
QUALIFY ROW_NUMBER() OVER (ORDER BY RUN_TS DESC) = 1;

SELECT * FROM DQ_LATEST_RUN;