USE ROLE ACCOUNTADMIN;
USE WAREHOUSE EDP_WH;
USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.RAW;

CREATE OR REPLACE TABLE OLIST_CUSTOMERS_RAW (
    CUSTOMER_ID    STRING,
    CUSTOMER_UNIQUE_ID STRING,
    CUSTOMER_ZIP_CODE_PREFIX  STRING,
    CUSTOMER_CITY STRING,
    CUSTOMER_STATE   STRING
);


CREATE OR REPLACE TABLE OLIST_ORDERS_RAW (
    ORDER_ID   STRING,
    CUSTOMER_ID   STRING,
    ORDER_STATUS  STRING,
    ORDER_PURCHASE_TIMESTAMP TIMESTAMP_NTZ,
    ORDER_APPROVED_AT  TIMESTAMP_NTZ,
    ORDER_DELIVERED_CARRIER_DATE  TIMESTAMP_NTZ,
    ORDER_DELIVERED_CUSTOMER_DATE  TIMESTAMP_NTZ,
    ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE OLIST_ORDER_ITEMS_RAW (
    ORDER_ID STRING,
    ORDER_ITEM_ID NUMBER,
    PRODUCT_ID STRING,
    SELLER_ID  STRING,
    SHIPPING_LIMIT_DATE TIMESTAMP_NTZ,
    PRICE NUMBER(12,2),
    FREIGHT_VALUE NUMBER(12,2)
);

CREATE OR REPLACE TABLE OLIST_ORDER_PAYMENTS_RAW (
    ORDER_ID STRING,
    PAYMENT_SEQUENTIAL NUMBER,
    PAYMENT_TYPE  STRING,
    PAYMENT_INSTALLMENTS NUMBER,
    PAYMENT_VALUE NUMBER(12,2)
);

SHOW TABLES LIKE 'OLIST_%_RAW';

SELECT COUNT(*) 
FROM OLIST_CUSTOMERS_RAW;