USE ROLE ACCOUNTADMIN;
USE WAREHOUSE EDP_WH;
USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.RAW;


COPY INTO OLIST_CUSTOMERS_RAW
FROM @AZURE_ENTERPRISE_STAGE/olist_customers_dataset.csv
FILE_FORMAT = CSV_FORMAT
FORCE = TRUE;

COPY INTO OLIST_ORDERS_RAW
FROM @AZURE_ENTERPRISE_STAGE/olist_orders_dataset.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO OLIST_ORDER_ITEMS_RAW
FROM @AZURE_ENTERPRISE_STAGE/olist_order_items_dataset.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO OLIST_ORDER_PAYMENTS_RAW
FROM @AZURE_ENTERPRISE_STAGE/olist_order_payments_dataset.csv
FILE_FORMAT = CSV_FORMAT;

SELECT COUNT(*) AS payments_count 
FROM OLIST_ORDER_PAYMENTS_RAW;


USE ROLE ACCOUNTADMIN;

SHOW WAREHOUSES LIKE 'EDP_WH';
SHOW DATABASES LIKE 'ENTERPRISE_DATA_PLATFORM_DB';

-- test actual usage
USE WAREHOUSE EDP_WH;
USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA STAGING;

SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA STAGING;
show views in schema ENTERPRISE_DATA_PLATFORM_DB.RAW;
show tables in schema ENTERPRISE_DATA_PLATFORM_DB.RAW;

show views like '%STG_CUSTOMERS%' in schema ENTERPRISE_DATA_PLATFORM_DB.STAGING;


SELECT COUNT(*) FROM ENTERPRISE_DATA_PLATFORM_DB.STAGING.STG_CUSTOMERS;


USE WAREHOUSE EDP_WH;
USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA STAGING;

SELECT COUNT(*) AS raw_cnt
FROM ENTERPRISE_DATA_PLATFORM_DB.RAW.OLIST_CUSTOMERS_RAW;

SELECT COUNT(*) AS stg_cnt
FROM ENTERPRISE_DATA_PLATFORM_DB.STAGING.STG_CUSTOMERS;