USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE EDP_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE EDP_WH;
CREATE OR REPLACE DATABASE ENTERPRISE_DATA_PLATFORM_DB;

USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
CREATE OR REPLACE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.RAW;
CREATE OR REPLACE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.STAGING;
CREATE OR REPLACE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.MART;
CREATE OR REPLACE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.OPS;
CREATE OR REPLACE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.DQ;
CREATE OR REPLACE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.META;
CREATE OR REPLACE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.SECURITY;


USE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.RAW;


SHOW DATABASES LIKE 'ENTERPRISE_DATA_PLATFORM_DB';
SHOW SCHEMAS  IN DATABASE ENTERPRISE_DATA_PLATFORM_DB;

USE ROLE ACCOUNTADMIN;

-- set context
USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MART;
CREATE SCHEMA IF NOT EXISTS OPS;
CREATE SCHEMA IF NOT EXISTS DQ;
CREATE SCHEMA IF NOT EXISTS META;


SHOW SCHEMAS IN DATABASE ENTERPRISE_DATA_PLATFORM_DB;

USE SCHEMA RAW;
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();

SHOW SCHEMAS IN DATABASE ENTERPRISE_DATA_PLATFORM_DB;
