USE ROLE ACCOUNTADMIN;
USE WAREHOUSE EDP_WH;
USE DATABASE ENTERPRISE_DATA_PLATFORM_DB;
USE SCHEMA ENTERPRISE_DATA_PLATFORM_DB.RAW;


CREATE OR REPLACE STAGE AZURE_ENTERPRISE_STAGE
    URL = 'azure://sreyasdataengineering.blob.core.windows.net/enrerprise-data'
    CREDENTIALS = (AZURE_SAS_TOKEN = '?sp=rl&st=2026-02-19T03:07:11Z&se=2026-02-20T11:22:11Z&spr=https&sv=2024-11-04&sr=c&sig=hTuAuaD59JX7s7dxW0dCb3B%2F3pOzqyP4sPTHf3ceWmA%3D')
    FILE_FORMAT = CSV_FORMAT;
LIST @AZURE_ENTERPRISE_STAGE;